project_id = "kpjshxyooydarthruxuh"

[functions.search]
verify_jwt = false

[functions.autocomplete]
verify_jwt = false

[functions.ai-summary]
verify_jwt = false

[functions.image-search]
verify_jwt = false